### PR TITLE
Create answer.json

### PR DESCRIPTION
**Pull request by nikhildewoolkar**
This is the resultant Json ... It is having some errors. check it out.

### CODE REVIEW

**Comment by nikhildewoolkar** [comment]
review

**Review by jesuino — CHANGES_REQUESTED** [review]
There are some error with double double quotes (`""`). Could you please check it

**Comment by nikhildewoolkar** [comment]
> There are some error with double double quotes (`""`). Could you please check it

I have changed logic in code. So resultant JSON is updated n ans.json kindly check it once.

**Comment by jesuino** [comment]
Hello Nikhil,

Thanks for the update, I tested the JSON `ans.json` and it works!

Could you please rename it to something more meaningful? For example: oscar.json

Also please notice you are sending multiple files on this PR. You can go to your repo in the branch patch-1 and delete the duplicate file.

Thanks!

**Comment by jesuino** [comment]
I found a small problem with the JSON file: it includes the header.

Please skip the header

image

**Comment by nikhildewoolkar** [comment]
> I found a small problem with the JSON file: it includes the header.
> 
> Please skip the header
> 
> image

Done with this ... Just because we used java 11 api it is taking extra space complexity. normal variable not allowed.variable should be declared with final. in earlier logic it was getting handled efficiently. without extra space complexity. review my code and let me know update.

**Comment by jesuino** [comment]
Closing this since the fixed JSON was sent in another PR

**Pull request closed without merging**
